[package]
name = "rust-token-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.11.1"
candid = "0.9.9"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
ic-cdk-macros = "0.8.1"